/*
 *
 * JarvisCustomer constants
 *
 */

export const DEFAULT_ACTION = 'app/JarvisCustomer/DEFAULT_ACTION';
export const SAVE_DATA = 'SAVE DATA';
export const SAVE_RAW_DATA = 'SAVE_RAW_DATA';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const REQUEST_OTP = 'REQUEST_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILURE = 'REQUEST_COUNTRIES_FAILURE';
export const REQUEST_PROVINCES = 'REQUEST_PROVINCES';
export const REQUEST_PROVINCES_SUCCESS = 'REQUEST_PROVINCES_SUCCESS';
export const REQUEST_SELECTION_SUCCESS = 'REQUEST_SELECTION_SUCCESS';
export const REQUEST_COMPANIES_SUCCESS = 'REQUEST_COMPANIES_SUCCESS';
export const REQUEST_COMPANIES_SEARCH = 'REQUEST_COMPANIES_SEARCH';
export const REQUEST_PROVINCES_FAILURE = 'REQUEST_PROVINCES_FAILURE';
export const CHECK_LOS_ROUND1 = 'CHECK_LOS_ROUND1';
export const UPLOAD_VIDEO_PENDING = 'UPLOAD_VIDEO_PENDING';
export const CHECK_LOS_RESULT_ROUND1 = 'CHECK_LOS_RESULT_ROUND1';
export const CHECK_LOS_RESULT_ROUND2 = 'CHECK_LOS_RESULT_ROUND2';
export const CHECK_LOS_ROUND2 = 'CHECK_LOS_ROUND2';
export const SAVE_DATA_APP = 'SAVE_DATA_APP';
export const UPLOAD_OCR_FRONT = 'UPLOAD_OCR_FRONT';
export const UPLOAD_OCR_BACK = 'UPLOAD_OCR_BACK';
export const FACE_MATCHING = 'FACE_MATCHING';
export const REGISTER = 'REGISTER';
export const GET_DETAIL = 'GET_DETAIL';
export const LOGIN = 'LOGIN';
export const GET_DETAIL_APP_BY_TOKEN = 'GET_DETAIL_APP_BY_TOKEN';
export const GET_ALL_CARD = 'GET_ALL_CARD';
export const GET_ALL_CARD_SUCCESS = 'GET_ALL_CARD_SUCCESS';
export const GET_BRANCHES = 'GET_BRANCHES';
export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
export const GET_DOC_REQUIRED = 'GET_DOC_REQUIRED';
export const GET_DOC_REQUIRED_SUCCESS = 'GET_DOC_REQUIRED_SUCCESS';
export const GET_DOC_APP = 'GET_DOC_APP';
export const GET_DOC_APP_SUCCESS = 'GET_DOC_APP_SUCCESS';
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const GET_SHOW_VIRTUAL_CARD = 'GET_SHOW_VIRTUAL_CARD';
export const GET_SHOW_VIRTUAL_CARD_SUCCESS = 'GET_SHOW_VIRTUAL_CARD_SUCCESS';
export const CHECK_LOS_ROUND3 = 'CHECK_LOS_ROUND3';
export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
