/*
 *
 * JarvisCustomer constants
 *
 */

export const DEFAULT_ACTION = 'app/JarvisCustomer/DEFAULT_ACTION';
export const SAVE_DATA = 'SAVE DATA';
export const SAVE_RAW_DATA = 'SAVE_RAW_DATA';
export const SAVE_DATA_SUCCESS = 'SAVE_DATA_SUCCESS';
export const REQUEST_COUNTRIES = 'REQUEST_COUNTRIES';
export const REQUEST_OTP = 'REQUEST_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const REQUEST_COUNTRIES_SUCCESS = 'REQUEST_COUNTRIES_SUCCESS';
export const REQUEST_COUNTRIES_FAILURE = 'REQUEST_COUNTRIES_FAILURE';
export const REQUEST_PROVINCES = 'REQUEST_PROVINCES';
export const REQUEST_PROVINCES_SUCCESS = 'REQUEST_PROVINCES_SUCCESS';
export const REQUEST_SELECTION_SUCCESS = 'REQUEST_SELECTION_SUCCESS';
export const REQUEST_PROVINCES_FAILURE = 'REQUEST_PROVINCES_FAILURE';
export const CHECK_LOS_ROUND1 = 'CHECK_LOS_ROUND1';
export const UPLOAD_VIDEO_PENDING = 'UPLOAD_VIDEO_PENDING';
