export const DEFAULT_ACTION = 'app/App/DEFAULT_ACTION';
export const REQUEST_PENDING = 'app/App/REQUEST_PENDING';
export const REQUEST_SUCCESS = 'app/App/REQUEST_SUCCESS';
export const REQUEST_ERROR = 'app/App/REQUEST_ERROR';

export const GET_PROFESSIONS_PENDING = 'app/App/GET_PROFESSIONS_PENDING';
export const GET_PROFESSIONS_SUCCESS = 'app/App/GET_PROFESSIONS_SUCCESS';
export const GET_PROFESSIONS_ERROR = 'app/App/GET_PROFESSIONS_ERROR';
